[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.90"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
witchhat-core = { path = "crates/witchhat-core" }
arrow-array = "56"
arrow-schema = "56"
arrow-select = "56"
arrow-row = "56"
arrow-buffer = "56"
thiserror = "2.0.20"
xxhash-rust = { version = "0.8", features = ["xxh3"] }
serde_json = "1"
regex = "1"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
